export const products = [
  {
    id: "001",
    category: "Mobile",
    name: "MI Bag",
    price: 1200,
    pic: "https://m.media-amazon.com/images/I/71edjA10hZL._AC_UL320_.jpg",
  },
  {
    id: "002",
    category: "Mobile",
    name: "Bluetooth",
    price: 3000,
    pic: "https://m.media-amazon.com/images/I/51HBom8xz7L._AC_UL320_.jpg",
  },
  {
    id: "003",
    category: "Mobile",
    name: "Shoes",
    price: 500,
    pic: "https://m.media-amazon.com/images/I/61AjKQSFMhL._AC_UL320_.jpg",
  },
  {
    id: "004",
    category: "Mobile",
    name: "Laptop",
    price: 99200,
    pic: "https://m.media-amazon.com/images/I/61HCEPIeOmL._AC_UL320_.jpg",
  },
  {
    id: "005",
    category: "Mobile",
    name: "IQO000 Phones",
    price: 7000,
    pic: "https://m.media-amazon.com/images/I/615CXlFtDDS._AC_UL320_.jpg",
  },
  {
    id: "006",
    category: "Mobile",
    name: "Mouse Pad",
    price: 200,
    pic: "https://m.media-amazon.com/images/I/61G5-hNFMYL._AC_UL320_.jpg",
  },
  {
    id: "007",
    category: "Mobile",
    name: "Wifi Router V1",
    price: 3200,
    pic: "https://m.media-amazon.com/images/I/51GyT8KanJL._AC_UL320_.jpg",
  },
  {
    id: "008",
    category: "Mobile",
    name: "Wifi Router v2",
    price: 9200,
    pic: "https://m.media-amazon.com/images/I/51GyT8KanJL._AC_UL320_.jpg",
  },
  {
    id: "009",
    category: "Mobile",
    name: "Perfume",
    price: 200,
    pic: "https://m.media-amazon.com/images/I/41v0ZnX8QgL._AC_UL320_.jpg",
  },
  {
    id: "010",
    category: "Mobile",
    name: "RGB Keyboard",
    price: 1200,
    pic: "https://m.media-amazon.com/images/I/61NKGdlO36L._AC_UL320_.jpg",
  },
  {
    id: "011",
    category: "Mobile",
    name: "Gaming laptop",
    price: 200000,
    pic: "https://m.media-amazon.com/images/I/41Diz41FkhL._AC_SY200_.jpg",
  },
  {
    id: "012",
    category: "Mobile",
    name: "S20 5G",
    price: 40000,
    pic: "https://m.media-amazon.com/images/I/41ezRvTwcaL._AC_SY200_.jpg",
  },
  {
    id: "013",
    category: "Mobile",
    name: "Truke",
    price: 1200,
    pic: "https://m.media-amazon.com/images/I/41Bx4W9YwbL._AC_SY200_.jpg",
  },
  {
    id: "014",
    category: "Mobile",
    name: "Mobiles",
    price: 40900,
    pic: "https://m.media-amazon.com/images/I/41pjhU0OUwL._AC_SY200_.jpg",
  },
  {
    id: "015",
    category: "Mobile",
    name: "Mobile Holder ",
    price: 2200,
    pic: "https://m.media-amazon.com/images/I/31OjDYrw0ZL._AC_SY200_.jpg",
  },
  {
    id: "016",
    category: "Mobile",
    name: "Game Gear",
    price: 2000,
    pic: "https://m.media-amazon.com/images/I/41n2MqMIH5L._AC_SY200_.jpg",
  },
  {
    id: "017",
    category: "Mobile",
    name: "Vivo Mobiles",
    price: 18900,
    pic: "https://m.media-amazon.com/images/I/41+sLJHyA8L._AC_SY200_.jpg",
  },
  {
    id: "018",
    category: "Mobile",
    name: "Duracell",
    price: 200,
    pic: "https://m.media-amazon.com/images/I/415nVOD7bWL._AC_SY200_.jpg",
  },
  {
    id: "019",
    category: "Mobile",
    name: "Mivi Speakers",
    price: 1200,
    pic: "https://m.media-amazon.com/images/I/512SMIvhtPL._AC_SY200_.jpg",
  },
  {
    id: "020",
    category: "Mobile",
    name: "Coffee beans",
    price: 200,
    pic: "https://m.media-amazon.com/images/I/51bMH0uUNaL._AC_SY200_.jpg",
  },
  {
    id: "021",
    category: "Mobile",
    name: "Sasta filter",
    price: 2000,
    pic: "https://m.media-amazon.com/images/I/41chkwxm5hL._AC_SY200_.jpg",
  },
  {
    id: "022",
    category: "Mobile",
    name: "Sofa ",
    price: 200900,
    pic: "https://m.media-amazon.com/images/I/612h6HxucoL._AC_SY200_.jpg",
  },
  {
    id: "023",
    category: "Mobile",
    name: "Kacha Badam",
    price: 12200,
    pic: "https://m.media-amazon.com/images/I/51B8XAcZ0lL.jpg",
  },
  {
    id: "024",
    category: "Mobile",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p2.png",
  },
  {
    id: "025",
    category: "Mobile",
    name: "Frok v1",
    price: 1200,
    pic: "https://technext.github.io/famms/images/p3.png",
  },
  {
    id: "026",
    category: "Mobile",
    name: "Frok v2",
    price: 2100,
    pic: "https://technext.github.io/famms/images/p4.png",
  },
  {
    id: "027",
    category: "Mobile",
    name: "Frok v3",
    price: 2200,
    pic: "https://technext.github.io/famms/images/p5.png",
  },
  {
    id: "028",
    category: "Mobile",
    name: "Double Frok v1",
    price: 2000,
    pic: "https://technext.github.io/famms/images/p6.png",
  },
  {
    id: "029",
    category: "Mobile",
    name: "Harry Porter Cap",
    price: 200,
    pic: "https://technext.github.io/famms/images/p7.png",
  },
  {
    id: "030",
    category: "Mobile",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p8.png",
  },
  {
    id: "031",
    category: "Mobile",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p9.png",
  },
 
];
