export const products = [
  {
    id: "001",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p10.png",
  },
  {
    id: "002",
    name: "Shirt",
    price: 300,
    pic: "https://technext.github.io/famms/images/p11.png",
  },
  {
    id: "003",
    name: "Shirt",
    price: 500,
    pic: "https://technext.github.io/famms/images/p12.png",
  },
  {
    id: "004",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p1.png",
  },
  {
    id: "005",
    name: "Shirt",
    price: 700,
    pic: "https://technext.github.io/famms/images/p2.png",
  },
  {
    id: "006",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p3.png",
  },
  {
    id: "007",
    name: "Shirt",
    price: 300,
    pic: "https://technext.github.io/famms/images/p4.png",
  },
  {
    id: "008",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p5.png",
  },
  {
    id: "009",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p6.png",
  },
  {
    id: "010",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p7.png",
  },
  {
    id: "011",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p8.png",
  },
  {
    id: "012",
    name: "Shirt",
    price: 400,
    pic: "https://technext.github.io/famms/images/p9.png",
  },
  {
    id: "013",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p10.png",
  },
  {
    id: "014",
    name: "Shirt",
    price: 400,
    pic: "https://technext.github.io/famms/images/p10.png",
  },
  {
    id: "015",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p10.png",
  },
  {
    id: "016",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p10.png",
  },
  {
    id: "017",
    name: "Shirt",
    price: 800,
    pic: "https://technext.github.io/famms/images/p10.png",
  },
  {
    id: "018",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p10.png",
  },
  {
    id: "019",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p10.png",
  },
  {
    id: "020",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p10.png",
  },
  {
    id: "021",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p11.png",
  },
  {
    id: "022",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p12.png",
  },
  {
    id: "023",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p1.png",
  },
  {
    id: "024",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p2.png",
  },
  {
    id: "025",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p3.png",
  },
  {
    id: "026",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p4.png",
  },
  {
    id: "027",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p5.png",
  },
  {
    id: "028",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p6.png",
  },
  {
    id: "029",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p7.png",
  },
  {
    id: "030",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p8.png",
  },
  {
    id: "031",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p9.png",
  },
  {
    id: "032",
    name: "Shirt",
    price: 200,
    pic: "https://technext.github.io/famms/images/p9.png",
  },
];
